[package]
name = "ali_ecs"
version = "0.3.0"
authors = ["Tsohg <asaneoil@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
queues = "1.0.0"
variant_count = "1.1"
